version: "3"
services:
  snowboard-sample:
    container_name: snowboard-sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - "./doc:/doc"
    command: snowboard http -c /doc/config.yaml /doc/API.apib
