version: "3"
services:
  snowboard-sample:
    container_name: snowboard-sample
    image: quay.io/bukalapak/snowboard:v3.7.5
    ports:
      - "8088:8088"
    volumes:
      - "./doc:/doc"
    command: http -c /doc/config.yaml /doc/API.apib
